# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  TMP_IMAGE: $CI_REGISTRY_IMAGE/tmp:$CI_COMMIT_SHA

services:
  - docker:stable-dind

stages:
  - ruby
  - build
  - test
  - downstream
  - tag
  - deploy

.ruby:
  stage: ruby
  image: ruby:2.3

ruby test:
  extends: .ruby
  script:
    - bundle install
    - rspec spec --exclude-pattern '*/gemnasium_spec.rb'
  only:
    - branches

ruby gemnasium test:
  stage: ruby
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium:2.3.0
  script:
    - apk add --no-cache ruby-bundler
    - export GEMNASIUM_PATH="/gemnasium"
    - bundle install
    - bundle exec rspec spec --exclude-pattern '*/gemnasium_spec.rb'
  only:
    - branches

ruby lint:
  extends: .ruby
  script:
    - bundle install
    - bundle exec rubocop
  only:
    - branches

build commit:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $TMP_IMAGE --build-arg DS_ANALYZER_IMAGE_TAG=$MAJOR .
    - docker push $TMP_IMAGE

integration test:
  image: docker:stable
  stage: test
  variables:
    DS_ANALYZER_IMAGE_TAG: $MAJOR
  script:
    - echo "TODO"

.qa-downstream-ds:
  stage: downstream
  variables:
    SAST_DISABLED: "true"
    CONTAINER_SCANNING_DISABLED: "true"
    DAST_DISABLED: "true"
    LICENSE_MANAGEMENT_DISABLED: "true"
    DS_DISABLE_DIND: "false"
    DS_IMAGE: $CI_REGISTRY_IMAGE/tmp
    DS_VERSION: $CI_COMMIT_SHA
  trigger:
    project: ""
    branch: dep-scan-11-5-stable
    strategy: depend

java-maven-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/java-maven

js-npm-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/js-npm

js-yarn-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/js-yarn

php-composer-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/php-composer

python-pip-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/python-pip

ruby-bundler-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/ruby-bundler

.docker_tag:
  image: docker:stable
  stage: tag
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export SOURCE_IMAGE=$TMP_IMAGE
    - export TARGET_IMAGE=$CI_REGISTRY_IMAGE:${IMAGE_TAG:-$CI_JOB_NAME}
    - docker pull $SOURCE_IMAGE
    - docker tag $SOURCE_IMAGE $TARGET_IMAGE
    - docker push $TARGET_IMAGE

tag branch:
  extends: .docker_tag
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master

tag edge:
  extends: .docker_tag
  variables:
    IMAGE_TAG: edge
  only:
    - master

tag version:
  extends: .docker_tag
  before_script:
    - export IMAGE_TAG=${CI_COMMIT_TAG/v/}
    - echo "Checking that $CI_COMMIT_TAG is last in the changelog"
    - test "$(grep '^## v' CHANGELOG.md |head -n 1)" = "## $CI_COMMIT_TAG"
  only:
    - tags
  when: manual

.release:
  extends: .docker_tag
  stage: deploy
  only:
    - tags

major:
  extends: .release
  variables:
    IMAGE_TAG: $MAJOR

latest:
  extends: .release

11-5-stable:
  extends: .release

11-4-stable:
  extends: .release

11-3-stable:
  extends: .release

11-2-stable:
  extends: .release

11-1-stable:
  extends: .release

11-0-stable:
  extends: .release

10-8-stable:
  extends: .release

10-7-stable:
  extends: .release

include:
  - template: SAST.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

container_scanning:
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/tmp
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
