# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  TMP_IMAGE: $CI_REGISTRY_IMAGE/tmp:$CI_COMMIT_SHA

services:
  - docker:stable-dind

stages:
  - build
  - downstream

build commit:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $TMP_IMAGE --build-arg DS_ANALYZER_IMAGE_TAG=$MAJOR .
    - docker push $TMP_IMAGE

.qa-downstream-ds:
  stage: downstream
  variables:
    SAST_DISABLED: "true"
    CONTAINER_SCANNING_DISABLED: "true"
    DAST_DISABLED: "true"
    LICENSE_MANAGEMENT_DISABLED: "true"
    DS_DISABLE_DIND: "false"
    DS_IMAGE: $CI_REGISTRY_IMAGE/tmp
    DS_VERSION: $CI_COMMIT_SHA
  trigger:
    project: ""
    branch: dep-scan-11-5-stable
    strategy: depend

js-npm-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/js-npm

js-yarn-qa:
  extends: .qa-downstream-ds
  trigger:
    project: gitlab-org/security-products/tests/js-yarn
