AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: false
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'


Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
